local util = require "example.util"
local dscreen = require "dscreen.dscreen"

function init(self)
	gui.set_render_order(1)
	msg.post("#", util.acquire_input_focus)
end

function on_input(self, action_id, action)
	if action.pressed then
		if action_id == util.t then
			dscreen.pop_screen()
		end
	end
end

function on_message(self, message_id, message, sender)
	dscreen.on_message(message_id, message, sender)
end